global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'kafka-redpanda-comparison'
    environment: 'performance-testing'

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    metrics_path: /metrics

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s
    metrics_path: /metrics

  # Kafka JMX Exporter
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka-jmx-exporter:8080']
    scrape_interval: 10s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: kafka-jmx-exporter:8080

  # Kafka Brokers JMX (direct)
  - job_name: 'kafka-brokers'
    static_configs:
      - targets: 
        - 'kafka-broker-1:9101'
        - 'kafka-broker-2:9102'
        - 'kafka-broker-3:9103'
    scrape_interval: 10s
    metrics_path: /metrics

  # Redpanda metrics
  - job_name: 'redpanda'
    static_configs:
      - targets:
        - 'redpanda-1:9644'
        - 'redpanda-2:9644'
        - 'redpanda-3:9644'
    scrape_interval: 10s
    metrics_path: /metrics

  # Redpanda Node Exporter
  - job_name: 'redpanda-node-exporter'
    static_configs:
      - targets: ['redpanda-metrics-exporter:9100']
    scrape_interval: 5s

  # Kafka Lag Exporter
  - job_name: 'kafka-lag-exporter'
    static_configs:
      - targets: ['redpanda-lag-exporter:9999']
    scrape_interval: 30s

  # Performance Test Clients (will be added dynamically)
  - job_name: 'test-clients'
    static_configs:
      - targets: []
    scrape_interval: 5s
    honor_labels: true

  # Custom application metrics
  - job_name: 'performance-analyzer'
    static_configs:
      - targets: ['performance-analyzer:8090']
    scrape_interval: 10s
    metrics_path: /metrics

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "http://remote-prometheus:9090/api/v1/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500